default: &default
  adapter:  postgresql
  host:     ""
  encoding: unicode
  pool:     5
  template: template0
  password: <%= ENV['DB_PASS'] %>


development:
  <<: *default
  database: trip_reg_sulej_development


test:
  <<: *default
  database: trip_reg_sulej_test

production:
  <<: *default
  username: myapp
  database: trip_reg_sulej_production

