# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  domain_name: example.com
  secret_key_base: 1a7728207fcec93e3210092fa6ce9859f509b5cddab6fe096bae10d0198f4721b526e0169960188192b4b92f2733a42c52014abf5a9afcb6b3b6144842f7db3f

test:
  secret_key_base: ac2cd7dc09e1423b6ea916d6d0c010e865a46a668cefbdd4e13ea82a7abb1578fb501ff210c7d91c71ed25ea280edcfa6a4a83c91b04e64df1fe44c1cb0ca200

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
